server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858